#!/usr/bin/env python

import sys

from summoner import *

if __name__ == "__main__":
    if len(sys.argv) == 1:
        usage()
    elif sys.argv[1] == "init":
        init()
    elif sys.argv[1] == "create":
        create(sys.argv[2])
    else:
        clipboard(sys.argv[1])
